#!/bin/zsh
# Markers:
#   START: \x1b]123;START\x07<user> <pwd> >>>
#   END:   \x1b]123;<exit_code>;<uuid>;DONE\x07

_jg_emit_start_marker() {
    printf '\033]123;START\007%s %s >>>\n' "$(whoami)" "$(pwd)"
}

add-zsh-hook preexec _jg_emit_start_marker 2>/dev/null || {
    autoload -Uz add-zsh-hook 2>/dev/null
    add-zsh-hook preexec _jg_emit_start_marker
}

PS1='$(printf "\033]123;$?;${JG_BLOCK_UUID};DONE\007\n")'
